### ISSUE TITLE
Form - Validation styling 

### ISSUE THREAD

**Issue by thatericsmith** [jeremypbeasley/rest_fundaday#38]
Here's a screenie

![img_3413](https://cloud.githubusercontent.com/assets/933123/16849035/70754ffa-49ad-11e6-821a-2510a3e18c19.PNG)

**Comment by thatericsmith** [comment]
Ok - got these roughed in with 8a5c26cf5e3881f8f536772ac551bd46416ff59c

Adds a `div.error` with the error message

**Comment by jeremypbeasley** [comment]
Looks awesome. I'll get to styling it.
