### ISSUE TITLE
Form - Labels not collapsing when autocomplete fills the fields

### ISSUE THREAD

**Issue by jeremypbeasley** [jeremypbeasley/rest_fundaday#44]
and it looks whack.
![screenshot-fund-a-day iwantrest com 2016-07-26 00-23-26](https://cloud.githubusercontent.com/assets/5099620/17129326/39b5cf62-52c7-11e6-8f6c-fb6157fd0755.png)

**Comment by thatericsmith** [comment]
Ok - tried to fix this in: 9821b7ad3bfa0d855d8ef5827d1c2b5aaa3f4638

Let me know if that does it

**Comment by jeremypbeasley** [comment]
Looks great to me! Closing.
